name: Deploy Application

on:
  push:
    branches:
      - dev  # or any branch you want the deployment to trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version you prefer

      - name: Install dependencies
        run: npm install

      # Step 4: Deploy the code via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}  # Add the host as a secret in GitHub Actions
          username: ubuntu  # Add the server username as a secret
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add the private SSH key as a secret
          port: 22  # Optional, set this if not using default SSH port
          script: |
            cd /home/ubuntu/FrontEnd/vsystech-ui || exit 1
           
            sudo ./codeupdate.sh || exit 1 
            